# docker-compose.yml

version: "3.8"
services:
  api:
    build: .
    container_name: fastapi-controles
    ports:
      - "9500:9500"
    environment:
      # Variável lida no database.py (DB_NAME)
      DB_NAME: "controles.db"
    volumes:
      # Monta o arquivo controles.db no host, para persistir
      - ./src:/src
    # Se quiser rodar em modo debug (auto reload):
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
